#!/usr/bin/env bash

# Install Composer dependencies
composer install --prefer-dist --no-scripts --no-dev --optimize-autoloader

# Install npm dependencies
npm install

# Build npm assets
npm run build

# Run Laravel setup commands
php artisan storage:link
php artisan migrate --force
php artisan config:cache
php artisan route:cache
php artisan view:cache
php artisan optimize