name: Main Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  setup-build:
    uses: ./.github/workflows/setup_build.yml

  call-merge-check:
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/merge_request.yml
    needs: setup-build
    secrets: inherit

  lint-and-prettier:
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/lint_and_prettier.yml
    needs: [setup-build, call-merge-check]
    secrets: inherit

  testing:
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/testing.yml
    needs: [setup-build, lint-and-prettier, call-merge-check]
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        attempt: [1, 2, 3]

  update-package-and-audit:
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/update_package_and_security_audit.yml
    needs: [setup-build, lint-and-prettier, call-merge-check, testing]
    secrets: inherit

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    needs: [setup-build]
    secrets: inherit
