name: Main Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-build:
    uses: ./.github/workflows/setup_build.yml
    with:
      branch: ${{ github.ref }}

  call-merge-check:
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/merge_request.yml
    needs: setup-build
    with:
      branch: ${{ github.head_ref }}
    secrets: inherit

  lint-and-prettier:
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/lint_and_prettier.yml
    needs: [setup-build, call-merge-check]
    with:
      branch: ${{ github.head_ref }}
    secrets: inherit

  testing:
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/testing.yml
    needs: [setup-build, lint-and-prettier, call-merge-check]
    secrets: inherit

  update-package-and-audit:
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/update_package_and_security_audit.yml
    needs: [setup-build, lint-and-prettier, call-merge-check, testing]
    with:
      branch: ${{ github.head_ref }}
    secrets: inherit

  sonarqube-scan:
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/sonarq.yml
    needs: [setup-build, lint-and-prettier, call-merge-check, update-package-and-audit, testing]
    secrets: inherit

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    needs: [setup-build]
    secrets: inherit
