name: Merge Request Check

on:
  workflow_call:
  workflow_dispatch:

jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"

      - name: Check for merge conflicts
        run: |
          git checkout main
          git pull origin main

          git checkout ${{ github.ref }}

          git merge --no-commit --no-ff main

          if [ $? -ne 0 ]; then
            echo "::error::Merge conflicts detected between ${{ github.ref }} and main"
            git merge --abort
            exit 1
          else
            echo "No merge conflicts detected."
            exit 0
          fi
        shell: bash
