name: Update Packages and Security Audit

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
  workflow_dispatch:

jobs:
  update-and-audit:
    runs-on: ubuntu-latest

    concurrency:
      group: lint-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress
          npm ci

      - name: Run Security Audit
        run: |
          composer audit
          npm audit

      - name: Update Dependencies
        run: |
          composer update
          npm update

      - name: Run security audit
        run: npx audit-ci --json > audit-report.json

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: audit-report.json

      - name: Configure Git
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"

      - name: Commit and Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain package.json)" ]; then
            git add package.json
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            git commit -m "Update packages and run security audit: $COMMIT_MESSAGE"
            git push https://$GH_TOKEN@github.com/${{ github.repository }}.git "HEAD:${{ inputs.branch }}"
          else
            echo "No changes to commit"
          fi
        shell: bash

      - name: Post audit report to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: audit-report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
